var Grapher;
(function(l){var m=function(){function c(a){this._selection={};this._radiusScale=d3.scale.sqrt();this._element=d3.select(a);this.reset()}Object.defineProperty(c.prototype,"dataSource",{set:function(a){this._dataSource=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"labelData",{set:function(a){this._labelData=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"xData",{set:function(a){this._xData=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"yData",
{set:function(a){this._yData=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"radiusData",{set:function(a){this._radiusData=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"colorData",{set:function(a){this._colorData=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"startTime",{set:function(a){this._startTime=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"endTime",{set:function(a){this._endTime=a},enumerable:!0,configurable:!0});
Object.defineProperty(c.prototype,"xScale",{set:function(a){this._xScale=a;this._xAxis=d3.svg.axis().orient("bottom").scale(this._xScale)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"yScale",{set:function(a){this._yScale=a;this._yAxis=d3.svg.axis().orient("left").scale(this._yScale)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"colorScale",{set:function(a){this._colorScale=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"xAxis",{get:function(){return this._xAxis},
enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"yAxis",{get:function(){return this._yAxis},enumerable:!0,configurable:!0});c.prototype.select=function(a){this._selection[a]=!0};c.prototype.startTransition=function(){this._diagram||this.draw();this._timeSliderPlayButton.style("display","none");this._timeSliderHead.style("display","block");var a=this._startTime.getTime(),b=this._endTime.getTime(),e=this._currentTime.getTime(),a=2E4*(b-e)/(b-a),c=d3.interpolate(this._currentTime,this._endTime),
d=this;this._diagram.transition().duration(a).ease("linear").tween("date",function(){return function(a){d.update(new Date(c(a)))}}).each("end",function(){d.stopTransition()})};c.prototype.stopTransition=function(){this._diagram&&this._diagram.transition().duration(0)};c.prototype.reset=function(){this.stopTransition();this._element.selectAll("*").remove();this._margin={top:20,right:20,bottom:80,left:40};var a=parseFloat(this._element.attr("width")),b=parseFloat(this._element.attr("height"));this._width=
a-this._margin.right-this._margin.left;this._height=b-this._margin.top-this._margin.bottom;this.xScale=d3.scale.linear();this.yScale=d3.scale.linear()};c.prototype.draw=function(){this.createScales();this.createColorAxis();this.createRadiusAxis();this.createTimeSlider();this._diagram=this._element.append("g").attr("transform","translate("+this._margin.left+","+this._margin.top+")");this.createRules();this.createItems()};c.prototype.createScales=function(){var a=this.computeDomain(this._xData),b=this.computeDomain(this._yData);
this._radiusDomain=this.computeDomain(this._radiusData);this._colorDomain=this.computeDomain(this._colorData);this.computeTimeDomain();a=this._xScale.domain(a).range([30,this._width-30-40]);this._xScale=this._xScale.domain([a.invert(0),a.invert(this._width)]).range([0,this._width]).clamp(!0);b=this._yScale.domain(b).range([30,this._height-30]);this._yScale=this._yScale.domain([b.invert(0),b.invert(this._height)]).range([this._height,0]).clamp(!0);this._radiusScale=this._radiusScale.domain([0,this._radiusDomain[1]]).range([2,
20]).clamp(!0);if(this._colorDomain){var a=[{stop:0,color:"#3e53ff"},{stop:.33,color:"#2ff076"},{stop:.5,color:"#d0ff2f"},{stop:.66,color:"#ffff2f"},{stop:1,color:"#ff2f2f"}],e=this._element.append("defs").append("linearGradient").attr("id","colorGradient").attr("x2","1");a.forEach(function(a){e.append("stop").attr("offset",a.stop).attr("stop-color",a.color)});b=a.map(function(a){return a.stop});a=a.map(function(a){return a.color});this._colorScale=d3.scale.linear().domain(b.map(d3.scale.linear().domain(this._colorDomain).invert)).range(a)}this._colorScale||
(this._colorScale=d3.scale.category10())};c.prototype.createRules=function(){var a=this._diagram.append("g").classed("rules",!0);a.append("g").classed("axis",!0).attr("transform","translate(0,"+this._height+")").call(this.xAxis.tickSize(2,0,2));a.append("g").classed("axis",!0).call(this.yAxis.tickSize(2,0,2));a.append("g").classed("grid",!0).attr("transform","translate(0,"+this._height+")").call(this.xAxis.tickSize(-this._height,0,-this._height).tickFormat(function(a){return""}));a.append("g").classed("grid",
!0).call(this.yAxis.tickSize(-this._width,0,-this._width).tickFormat(function(a){return""}));a.selectAll(".grid line").filter(function(a){return 0==a}).classed("origin",!0);a.append("text").attr("text-anchor","end").attr("x",this._width-3).attr("y",this._height-6).text(this._xData);a.append("text").attr("text-anchor","end").attr("x","-3").attr("y",11).attr("transform","rotate(-90)").text(this._yData)};c.prototype.createColorAxis=function(){if(this._colorDomain){var a=.25*this._width,b=this._margin.left,
e=+this._element.attr("height")-30,c=d3.scale.linear().domain(this._colorDomain).range([0,a]),d=[0,.5,1].map(d3.scale.linear().domain(this._colorDomain).invert),c=d3.svg.axis().orient("bottom").scale(c).tickSize(2,0,2).tickValues(d),b=this._element.append("g").attr("transform","translate("+b+","+e+")");b.append("g").classed("axis",!0).attr("transform","translate(0,9)").call(c);b.append("rect").attr("y",-3).attr("width",a).attr("height",10).style("fill","url(#colorGradient)");b.append("text").attr("text-anchor",
"start").attr("dy",-8).text(this._colorData)}};c.prototype.createRadiusAxis=function(){var a=.25*this._width,b=this._margin.left+(this._colorDomain?.32*this._width:0),e=+this._element.attr("height")-30,c=d3.scale.linear().domain([0,this._radiusDomain[1]]).range([0,a]),d=[0,.5,1].map(d3.scale.linear().domain([0,this._radiusDomain[1]]).invert),c=d3.svg.axis().orient("bottom").scale(c).tickSize(2,0,2).tickValues(d),b=this._element.append("g").attr("transform","translate("+b+","+e+")");b.append("g").classed("axis",
!0).attr("transform","translate(0,9)").call(c);for(e=0;5>e;e++)b.append("circle").attr("cx",e*a/4).attr("cy",2).attr("r",e+1).style("fill","#888");b.append("text").attr("text-anchor","start").attr("dy",-8).text(this._radiusData)};c.prototype.createTimeSlider=function(){var a=parseFloat(this._element.attr("width")),b=this._width*(this._colorDomain?.32:.64),a=a-this._margin.right-b,e=+this._element.attr("height")-30;this._timeScale=d3.time.scale().domain([this._startTime,this._endTime]).range([0,b]).clamp(!0);
for(var c=this._colorDomain?[0,.25,.5,.75,1]:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1],c=c.map(d3.scale.linear().domain([this._startTime,this._endTime]).invert),d=[],g=0;g<c.length;g++)d[g]=new Date(c[g]);var c=d3.svg.axis().orient("bottom").scale(this._timeScale).tickSize(11,0,11).tickValues(d).tickFormat(function(a){return a.getFullYear()}),h=this._element.append("g").attr("transform","translate("+a+","+e+")"),f=this;h.append("g").classed("axis",!0).call(c);a=function(){return h.append("rect").attr("rx",
2).attr("ry",2).attr("y",-1).attr("x",-3).attr("height",6)};a().attr("width",b+6).style("fill","#fff");this._timeSlider=a().style("fill","#ddd");a().attr("width",b+6).style("fill","none").style("stroke","#888");this._timeSliderPosition=h.append("g");this._timeSliderPosition.append("line").attr("y2",-8).style("stroke","#888");this._timeSliderPosition.append("text").attr("y",-10).attr("text-anchor","middle");this._timeSliderHead=h.append("g").attr("pointer-events","all").attr("cursor","ew-resize");
this._timeSliderHead.append("circle").attr("cy",2).attr("r",4).style("fill","none").style("stroke","#888").style("stroke-width","5.5px");this._timeSliderHead.append("circle").attr("cy",2).attr("r",20).style("fill","none").style("opacity",1);this._timeSliderHead.style("display","none");this._timeSliderHead.call(d3.behavior.drag().on("dragstart",function(){f._timeSliderDragged=!1}).on("drag",function(){f._timeSliderDragged=!0;f.stopTransition();var a=f._timeScale.invert(d3.event.x);f.update(a)}).on("dragend",
function(){f._timeSliderDragged&&0<f._endTime.getTime()-f._currentTime.getTime()&&(f._timeSliderPlayButton.style("display","block"),f._timeSliderHead.style("display","none"))}));this._timeSliderPlayButton=h.append("g").attr("transform","translate(0,2)").attr("pointer-events","all").attr("cursor","pointer");this._timeSliderPlayButton.append("circle").attr("cy",0).attr("r",6).style("fill","#fff").style("stroke","#888");this._timeSliderPlayButton.append("circle").attr("cy",0).attr("r",20).style("fill",
"none").style("opacity",1);this._timeSliderPlayButton.append("polygon").attr("points","-2,-3 -2,3 4,0").style("fill","#888");this._timeSliderPlayButton.on("click",function(){f.startTransition()})};c.prototype.updateTimeSlider=function(a){var b=this._timeScale(a);this._timeSlider.attr("width",b+6);this._timeSliderHead.attr("transform","translate("+b+",0)");this._timeSliderPosition.attr("transform","translate("+b+",0)");this._timeSliderPosition.selectAll("text").text(a.getFullYear());this._timeSliderPlayButton.attr("transform",
"translate("+b+",2)");0>=this._endTime.getTime()-a.getTime()&&(this._timeSliderHead.style("display","block"),this._timeSliderPlayButton.style("display","none"))};c.prototype.createItems=function(){var a=this;this._items=this._diagram.append("g").selectAll(".item").data(this._dataSource).enter().append("g").classed("item",!0).each(function(b){b=b[a._labelData];var c=d3.select(this);c.classed("selectedItem",a._selection[b]);c.append("text").classed("label",!0).attr("y",1).text(b);c.append("circle")}).on("click",
function(){d3.select(this).classed("selectedItem",!d3.select(this).classed("selectedItem"))});this.update(this._startTime)};c.prototype.computeDomain=function(a){var b=this,c=!0;b._dataSource.forEach(function(b){c=c&&b[a]instanceof Array||"number"==typeof b[a]});if(!c)return null;var k=d3.min(this._dataSource,function(b){return"number"==typeof b[a]?b[a]:d3.min(b[a],function(a){return a[1]})}),d=d3.max(this._dataSource,function(b){return"number"==typeof b[a]?b[a]:d3.max(b[a],function(a){return a[1]})});
b._dataSource.forEach(function(c){if(c[a]instanceof Array){var e=c[a].map(function(a){return a[0]}).map(function(a){return b.createDate(a)}),d=c[a].map(function(a){return a[1]});b._endTime&&e[e.length-1]<b._endTime&&(e.push(b._endTime),d.push(d[d.length-1]));c[a]=d3.time.scale().domain(e).range(d);c[a].__min=e[0];c[a].__max=e[e.length-1]}});return[k,d]};c.prototype.createDate=function(a){return"number"==typeof a?new Date(a,0,1):"string"==typeof a?new Date(a):a};c.prototype.computeTimeDomain=function(){var a=
this,b=this._startTime,c=this._endTime;[a._xData,a._yData,a._radiusData,a._colorData].forEach(function(k){a._dataSource.forEach(function(d){d=d[k];"number"!=typeof d&&"string"!=typeof d&&d.domain().forEach(function(d){a._startTime||b&&!(b>d)||(b=d);a._endTime||c&&!(c<d)||(c=d)})})});this._startTime=b;this._endTime=c};c.prototype.hasValue=function(a,b,c){a=a[b];return"number"==typeof a||"string"==typeof a?!0:c>=a.__min&&c<=a.__max};c.prototype.computeValue=function(a,b,c){return(a=a[b])&&a.constructor&&
a.call&&a.apply?a(c):a};c.prototype.update=function(a){this._currentTime=a;this.updateTimeSlider(a);var b=this;this._items.each(function(c){if(b.hasValue(c,b._xData,a)&&b.hasValue(c,b._yData,a)&&b.hasValue(c,b._radiusData,a)){var k=b._xScale(b.computeValue(c,b._xData,a)),d=b._yScale(b.computeValue(c,b._yData,a)),g=b.computeValue(c,b._radiusData,a),g=b._radiusScale(0>g?0:g);c=b.hasValue(c,b._colorData,a)?b._colorScale(b.computeValue(c,b._colorData,a)):"#fff";var h=1+1.1*g;d3.select(this).style("display",
"block");d3.select(this).attr("transform","translate("+k+","+d+")");d3.select(this).selectAll("circle").attr("r",g).style("fill",c);d3.select(this).selectAll("text").attr("transform","translate("+h+",0)")}else d3.select(this).style("display","none")});this._items.sort(function(a,c){return c[b.radiusData]-a[b.radiusData]})};return c}();l.MotionChart=m})(Grapher||(Grapher={}));
